version: '3.1'

services:

  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 8081:8081
